/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QWidget *Device;
    QWidget *lock_screen;
    QPushButton *pin1_button;
    QPushButton *pin2_button;
    QPushButton *pin3_button;
    QPushButton *submit_pin_button;
    QWidget *log_screen;
    QListWidget *loglist;
    QLabel *label;
    QWidget *personal_profiles_list_screen;
    QLabel *label_2;
    QListWidget *personal_profiles_list;
    QPushButton *personal_profiles_list_add_button;
    QWidget *current_status_screen;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_13;
    QLabel *label_5;
    QLabel *label_14;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *target_BG_label;
    QLabel *profile_name_label;
    QLabel *insulin_duration_label;
    QLabel *carb_ratio_label;
    QLabel *last_bolus_amount_label;
    QLabel *last_bolus_time_label;
    QLabel *basal_rate_label;
    QLabel *correction_factor_label;
    QWidget *options_screen;
    QLabel *label_7;
    QPushButton *stop_resume_button;
    QPushButton *logs_screen_button;
    QPushButton *personal_profiles_screen_button;
    QPushButton *setup_pin_screen_button;
    QWidget *setup_pin_screen;
    QLabel *label_8;
    QPushButton *setup_pin1_button;
    QPushButton *setup_pin2_button;
    QPushButton *setup_pin3_button;
    QLabel *current_pin_label;
    QPushButton *submit_setup_pin_button;
    QWidget *personal_profile_screen;
    QLabel *label_26;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_36;
    QLabel *label_43;
    QLineEdit *basal_rate_textbox;
    QLineEdit *carb_ratio_textbox;
    QLineEdit *correction_factor_textbox;
    QLineEdit *quick_bolus_textbox;
    QLineEdit *target_BG_textbox;
    QLineEdit *profile_name_textbox;
    QPushButton *delete_profile_button;
    QPushButton *activate_profile_button;
    QPushButton *edit_profile_button;
    QWidget *bolus_screen;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *bolus_target_BG_label;
    QLabel *bolus_insulin_duration_label;
    QLineEdit *bolus_current_BG_textbox;
    QLineEdit *bolus_carb_intake_textbox;
    QLineEdit *bolus_insulin_dose_textbox;
    QLineEdit *bolus_insulin_duration_textbox;
    QLineEdit *bolus_target_BG_textbox;
    QLabel *label_24;
    QRadioButton *default_radio_button;
    QRadioButton *extended_radio_button;
    QPushButton *bolus_ok_button;
    QWidget *home_screen;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *home_iob_label;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *home_time_label;
    QPushButton *home_options_button;
    QPushButton *home_bolus_button;
    QLabel *home_current_BG_label;
    QLabel *battery;
    QLabel *insulin_cartidge;
    QPushButton *home_button;
    QPushButton *current_status_button;
    QPushButton *recharge_button;
    QPushButton *insulin_refill_button;
    QPushButton *test_lock_button;
    QPushButton *test_log_button;
    QPushButton *test_profile_list_button;
    QPushButton *test_current_status_button;
    QPushButton *test_options_button;
    QPushButton *test_setup_pin_button;
    QPushButton *test_profile_button;
    QPushButton *test_bolus_button;
    QPushButton *power_button;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(951, 460);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        Device = new QWidget(centralwidget);
        Device->setObjectName(QString::fromUtf8("Device"));
        Device->setGeometry(QRect(0, 0, 831, 461));
        Device->setAutoFillBackground(false);
        Device->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        lock_screen = new QWidget(Device);
        lock_screen->setObjectName(QString::fromUtf8("lock_screen"));
        lock_screen->setGeometry(QRect(10, 40, 691, 411));
        lock_screen->setAutoFillBackground(false);
        lock_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        pin1_button = new QPushButton(lock_screen);
        pin1_button->setObjectName(QString::fromUtf8("pin1_button"));
        pin1_button->setGeometry(QRect(120, 150, 121, 101));
        pin1_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 36pt \"DejaVu Sans\";"));
        pin2_button = new QPushButton(lock_screen);
        pin2_button->setObjectName(QString::fromUtf8("pin2_button"));
        pin2_button->setGeometry(QRect(270, 150, 121, 101));
        pin2_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 36pt \"DejaVu Sans\";"));
        pin3_button = new QPushButton(lock_screen);
        pin3_button->setObjectName(QString::fromUtf8("pin3_button"));
        pin3_button->setGeometry(QRect(420, 150, 121, 101));
        pin3_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 36pt \"DejaVu Sans\";"));
        submit_pin_button = new QPushButton(lock_screen);
        submit_pin_button->setObjectName(QString::fromUtf8("submit_pin_button"));
        submit_pin_button->setGeometry(QRect(300, 300, 83, 41));
        submit_pin_button->setStyleSheet(QString::fromUtf8("background-color: rgb(38, 162, 105);"));
        log_screen = new QWidget(Device);
        log_screen->setObjectName(QString::fromUtf8("log_screen"));
        log_screen->setGeometry(QRect(10, 40, 691, 411));
        log_screen->setAutoFillBackground(false);
        log_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        loglist = new QListWidget(log_screen);
        loglist->setObjectName(QString::fromUtf8("loglist"));
        loglist->setGeometry(QRect(20, 50, 641, 341));
        loglist->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label = new QLabel(log_screen);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(300, 10, 61, 31));
        label->setStyleSheet(QString::fromUtf8("font: 75 20pt \"DejaVu Sans\";"));
        personal_profiles_list_screen = new QWidget(Device);
        personal_profiles_list_screen->setObjectName(QString::fromUtf8("personal_profiles_list_screen"));
        personal_profiles_list_screen->setGeometry(QRect(10, 40, 691, 411));
        personal_profiles_list_screen->setAutoFillBackground(false);
        personal_profiles_list_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        label_2 = new QLabel(personal_profiles_list_screen);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(240, 20, 231, 31));
        label_2->setStyleSheet(QString::fromUtf8("font: 75 20pt \"DejaVu Sans\";"));
        personal_profiles_list = new QListWidget(personal_profiles_list_screen);
        personal_profiles_list->setObjectName(QString::fromUtf8("personal_profiles_list"));
        personal_profiles_list->setGeometry(QRect(20, 60, 641, 341));
        personal_profiles_list->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        personal_profiles_list_add_button = new QPushButton(personal_profiles_list_screen);
        personal_profiles_list_add_button->setObjectName(QString::fromUtf8("personal_profiles_list_add_button"));
        personal_profiles_list_add_button->setGeometry(QRect(600, 10, 51, 41));
        personal_profiles_list_add_button->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        current_status_screen = new QWidget(Device);
        current_status_screen->setObjectName(QString::fromUtf8("current_status_screen"));
        current_status_screen->setGeometry(QRect(10, 40, 691, 411));
        current_status_screen->setAutoFillBackground(false);
        current_status_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        label_3 = new QLabel(current_status_screen);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(240, 20, 231, 31));
        label_3->setStyleSheet(QString::fromUtf8("font: 75 20pt \"DejaVu Sans\";"));
        label_4 = new QLabel(current_status_screen);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(60, 70, 261, 31));
        label_4->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_4->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(current_status_screen);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(60, 110, 261, 31));
        label_13->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_13->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(current_status_screen);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(60, 150, 261, 31));
        label_5->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_5->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(current_status_screen);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(60, 190, 261, 31));
        label_14->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_14->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(current_status_screen);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(60, 230, 261, 31));
        label_27->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_27->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(current_status_screen);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(60, 270, 261, 31));
        label_28->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_28->setAlignment(Qt::AlignCenter);
        label_37 = new QLabel(current_status_screen);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(60, 310, 261, 31));
        label_37->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_37->setAlignment(Qt::AlignCenter);
        label_38 = new QLabel(current_status_screen);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(60, 350, 261, 31));
        label_38->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_38->setAlignment(Qt::AlignCenter);
        target_BG_label = new QLabel(current_status_screen);
        target_BG_label->setObjectName(QString::fromUtf8("target_BG_label"));
        target_BG_label->setGeometry(QRect(360, 310, 261, 31));
        target_BG_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        target_BG_label->setAlignment(Qt::AlignCenter);
        profile_name_label = new QLabel(current_status_screen);
        profile_name_label->setObjectName(QString::fromUtf8("profile_name_label"));
        profile_name_label->setGeometry(QRect(360, 70, 261, 31));
        profile_name_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        profile_name_label->setAlignment(Qt::AlignCenter);
        insulin_duration_label = new QLabel(current_status_screen);
        insulin_duration_label->setObjectName(QString::fromUtf8("insulin_duration_label"));
        insulin_duration_label->setGeometry(QRect(360, 350, 261, 31));
        insulin_duration_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        insulin_duration_label->setAlignment(Qt::AlignCenter);
        carb_ratio_label = new QLabel(current_status_screen);
        carb_ratio_label->setObjectName(QString::fromUtf8("carb_ratio_label"));
        carb_ratio_label->setGeometry(QRect(360, 270, 261, 31));
        carb_ratio_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        carb_ratio_label->setAlignment(Qt::AlignCenter);
        last_bolus_amount_label = new QLabel(current_status_screen);
        last_bolus_amount_label->setObjectName(QString::fromUtf8("last_bolus_amount_label"));
        last_bolus_amount_label->setGeometry(QRect(360, 150, 261, 31));
        last_bolus_amount_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        last_bolus_amount_label->setAlignment(Qt::AlignCenter);
        last_bolus_time_label = new QLabel(current_status_screen);
        last_bolus_time_label->setObjectName(QString::fromUtf8("last_bolus_time_label"));
        last_bolus_time_label->setGeometry(QRect(360, 190, 261, 31));
        last_bolus_time_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        last_bolus_time_label->setAlignment(Qt::AlignCenter);
        basal_rate_label = new QLabel(current_status_screen);
        basal_rate_label->setObjectName(QString::fromUtf8("basal_rate_label"));
        basal_rate_label->setGeometry(QRect(360, 110, 261, 31));
        basal_rate_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        basal_rate_label->setAlignment(Qt::AlignCenter);
        correction_factor_label = new QLabel(current_status_screen);
        correction_factor_label->setObjectName(QString::fromUtf8("correction_factor_label"));
        correction_factor_label->setGeometry(QRect(360, 230, 261, 31));
        correction_factor_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        correction_factor_label->setAlignment(Qt::AlignCenter);
        options_screen = new QWidget(Device);
        options_screen->setObjectName(QString::fromUtf8("options_screen"));
        options_screen->setGeometry(QRect(10, 40, 691, 411));
        options_screen->setAutoFillBackground(false);
        options_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        label_7 = new QLabel(options_screen);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(240, 20, 231, 31));
        label_7->setStyleSheet(QString::fromUtf8("font: 75 20pt \"DejaVu Sans\";"));
        label_7->setAlignment(Qt::AlignCenter);
        stop_resume_button = new QPushButton(options_screen);
        stop_resume_button->setObjectName(QString::fromUtf8("stop_resume_button"));
        stop_resume_button->setGeometry(QRect(70, 100, 261, 101));
        stop_resume_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 75 20pt \"DejaVu Sans\";"));
        logs_screen_button = new QPushButton(options_screen);
        logs_screen_button->setObjectName(QString::fromUtf8("logs_screen_button"));
        logs_screen_button->setGeometry(QRect(360, 100, 261, 101));
        logs_screen_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 75 20pt \"DejaVu Sans\";"));
        personal_profiles_screen_button = new QPushButton(options_screen);
        personal_profiles_screen_button->setObjectName(QString::fromUtf8("personal_profiles_screen_button"));
        personal_profiles_screen_button->setGeometry(QRect(360, 240, 261, 101));
        personal_profiles_screen_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 75 20pt \"DejaVu Sans\";"));
        setup_pin_screen_button = new QPushButton(options_screen);
        setup_pin_screen_button->setObjectName(QString::fromUtf8("setup_pin_screen_button"));
        setup_pin_screen_button->setGeometry(QRect(70, 240, 261, 101));
        setup_pin_screen_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 75 20pt \"DejaVu Sans\";"));
        setup_pin_screen = new QWidget(Device);
        setup_pin_screen->setObjectName(QString::fromUtf8("setup_pin_screen"));
        setup_pin_screen->setGeometry(QRect(10, 40, 691, 411));
        setup_pin_screen->setAutoFillBackground(false);
        setup_pin_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        label_8 = new QLabel(setup_pin_screen);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(240, 30, 231, 31));
        label_8->setStyleSheet(QString::fromUtf8("font: 75 20pt \"DejaVu Sans\";"));
        label_8->setAlignment(Qt::AlignCenter);
        setup_pin1_button = new QPushButton(setup_pin_screen);
        setup_pin1_button->setObjectName(QString::fromUtf8("setup_pin1_button"));
        setup_pin1_button->setGeometry(QRect(90, 160, 131, 101));
        setup_pin1_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 75 20pt \"DejaVu Sans\";"));
        setup_pin2_button = new QPushButton(setup_pin_screen);
        setup_pin2_button->setObjectName(QString::fromUtf8("setup_pin2_button"));
        setup_pin2_button->setGeometry(QRect(290, 160, 131, 101));
        setup_pin2_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 75 20pt \"DejaVu Sans\";"));
        setup_pin3_button = new QPushButton(setup_pin_screen);
        setup_pin3_button->setObjectName(QString::fromUtf8("setup_pin3_button"));
        setup_pin3_button->setGeometry(QRect(490, 160, 131, 101));
        setup_pin3_button->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 95, 180);\n"
"font: 75 20pt \"DejaVu Sans\";"));
        current_pin_label = new QLabel(setup_pin_screen);
        current_pin_label->setObjectName(QString::fromUtf8("current_pin_label"));
        current_pin_label->setGeometry(QRect(200, 90, 301, 31));
        current_pin_label->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        current_pin_label->setAlignment(Qt::AlignCenter);
        submit_setup_pin_button = new QPushButton(setup_pin_screen);
        submit_setup_pin_button->setObjectName(QString::fromUtf8("submit_setup_pin_button"));
        submit_setup_pin_button->setGeometry(QRect(320, 310, 83, 41));
        submit_setup_pin_button->setStyleSheet(QString::fromUtf8("background-color: rgb(38, 162, 105);"));
        personal_profile_screen = new QWidget(Device);
        personal_profile_screen->setObjectName(QString::fromUtf8("personal_profile_screen"));
        personal_profile_screen->setGeometry(QRect(10, 40, 691, 411));
        personal_profile_screen->setAutoFillBackground(false);
        personal_profile_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        label_26 = new QLabel(personal_profile_screen);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(60, 80, 261, 31));
        label_26->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_26->setAlignment(Qt::AlignCenter);
        label_33 = new QLabel(personal_profile_screen);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(60, 130, 261, 31));
        label_33->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_33->setAlignment(Qt::AlignCenter);
        label_34 = new QLabel(personal_profile_screen);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(60, 180, 261, 31));
        label_34->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_34->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(personal_profile_screen);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(60, 230, 261, 31));
        label_36->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_36->setAlignment(Qt::AlignCenter);
        label_43 = new QLabel(personal_profile_screen);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(60, 280, 261, 31));
        label_43->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_43->setAlignment(Qt::AlignCenter);
        basal_rate_textbox = new QLineEdit(personal_profile_screen);
        basal_rate_textbox->setObjectName(QString::fromUtf8("basal_rate_textbox"));
        basal_rate_textbox->setGeometry(QRect(360, 80, 261, 31));
        basal_rate_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        carb_ratio_textbox = new QLineEdit(personal_profile_screen);
        carb_ratio_textbox->setObjectName(QString::fromUtf8("carb_ratio_textbox"));
        carb_ratio_textbox->setGeometry(QRect(360, 130, 261, 31));
        carb_ratio_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        correction_factor_textbox = new QLineEdit(personal_profile_screen);
        correction_factor_textbox->setObjectName(QString::fromUtf8("correction_factor_textbox"));
        correction_factor_textbox->setGeometry(QRect(360, 180, 261, 31));
        correction_factor_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        quick_bolus_textbox = new QLineEdit(personal_profile_screen);
        quick_bolus_textbox->setObjectName(QString::fromUtf8("quick_bolus_textbox"));
        quick_bolus_textbox->setGeometry(QRect(360, 280, 261, 31));
        quick_bolus_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        target_BG_textbox = new QLineEdit(personal_profile_screen);
        target_BG_textbox->setObjectName(QString::fromUtf8("target_BG_textbox"));
        target_BG_textbox->setGeometry(QRect(360, 230, 261, 31));
        target_BG_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        profile_name_textbox = new QLineEdit(personal_profile_screen);
        profile_name_textbox->setObjectName(QString::fromUtf8("profile_name_textbox"));
        profile_name_textbox->setGeometry(QRect(210, 10, 261, 51));
        profile_name_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        delete_profile_button = new QPushButton(personal_profile_screen);
        delete_profile_button->setObjectName(QString::fromUtf8("delete_profile_button"));
        delete_profile_button->setGeometry(QRect(50, 20, 111, 31));
        delete_profile_button->setStyleSheet(QString::fromUtf8("background-color: rgb(165, 29, 45);"));
        activate_profile_button = new QPushButton(personal_profile_screen);
        activate_profile_button->setObjectName(QString::fromUtf8("activate_profile_button"));
        activate_profile_button->setGeometry(QRect(290, 370, 111, 31));
        activate_profile_button->setStyleSheet(QString::fromUtf8("background-color: rgb(38, 162, 105);"));
        edit_profile_button = new QPushButton(personal_profile_screen);
        edit_profile_button->setObjectName(QString::fromUtf8("edit_profile_button"));
        edit_profile_button->setGeometry(QRect(520, 20, 111, 31));
        edit_profile_button->setStyleSheet(QString::fromUtf8("background-color: rgb(28, 113, 216);"));
        bolus_screen = new QWidget(Device);
        bolus_screen->setObjectName(QString::fromUtf8("bolus_screen"));
        bolus_screen->setGeometry(QRect(10, 40, 691, 411));
        bolus_screen->setAutoFillBackground(false);
        bolus_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        label_44 = new QLabel(bolus_screen);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(60, 70, 261, 31));
        label_44->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_44->setAlignment(Qt::AlignCenter);
        label_45 = new QLabel(bolus_screen);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(60, 110, 261, 31));
        label_45->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_45->setAlignment(Qt::AlignCenter);
        label_46 = new QLabel(bolus_screen);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(60, 150, 261, 31));
        label_46->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        label_46->setAlignment(Qt::AlignCenter);
        bolus_target_BG_label = new QLabel(bolus_screen);
        bolus_target_BG_label->setObjectName(QString::fromUtf8("bolus_target_BG_label"));
        bolus_target_BG_label->setGeometry(QRect(60, 280, 261, 31));
        bolus_target_BG_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        bolus_target_BG_label->setAlignment(Qt::AlignCenter);
        bolus_insulin_duration_label = new QLabel(bolus_screen);
        bolus_insulin_duration_label->setObjectName(QString::fromUtf8("bolus_insulin_duration_label"));
        bolus_insulin_duration_label->setGeometry(QRect(60, 320, 261, 31));
        bolus_insulin_duration_label->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        bolus_insulin_duration_label->setAlignment(Qt::AlignCenter);
        bolus_current_BG_textbox = new QLineEdit(bolus_screen);
        bolus_current_BG_textbox->setObjectName(QString::fromUtf8("bolus_current_BG_textbox"));
        bolus_current_BG_textbox->setGeometry(QRect(360, 70, 261, 31));
        bolus_current_BG_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        bolus_current_BG_textbox->setAlignment(Qt::AlignCenter);
        bolus_carb_intake_textbox = new QLineEdit(bolus_screen);
        bolus_carb_intake_textbox->setObjectName(QString::fromUtf8("bolus_carb_intake_textbox"));
        bolus_carb_intake_textbox->setGeometry(QRect(360, 110, 261, 31));
        bolus_carb_intake_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        bolus_carb_intake_textbox->setAlignment(Qt::AlignCenter);
        bolus_insulin_dose_textbox = new QLineEdit(bolus_screen);
        bolus_insulin_dose_textbox->setObjectName(QString::fromUtf8("bolus_insulin_dose_textbox"));
        bolus_insulin_dose_textbox->setGeometry(QRect(360, 150, 261, 31));
        bolus_insulin_dose_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        bolus_insulin_dose_textbox->setAlignment(Qt::AlignCenter);
        bolus_insulin_duration_textbox = new QLineEdit(bolus_screen);
        bolus_insulin_duration_textbox->setObjectName(QString::fromUtf8("bolus_insulin_duration_textbox"));
        bolus_insulin_duration_textbox->setGeometry(QRect(360, 320, 261, 31));
        bolus_insulin_duration_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        bolus_insulin_duration_textbox->setAlignment(Qt::AlignCenter);
        bolus_target_BG_textbox = new QLineEdit(bolus_screen);
        bolus_target_BG_textbox->setObjectName(QString::fromUtf8("bolus_target_BG_textbox"));
        bolus_target_BG_textbox->setGeometry(QRect(360, 280, 261, 31));
        bolus_target_BG_textbox->setStyleSheet(QString::fromUtf8("background-color: rgb(222, 221, 218);"));
        bolus_target_BG_textbox->setAlignment(Qt::AlignCenter);
        label_24 = new QLabel(bolus_screen);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(150, 20, 411, 31));
        label_24->setStyleSheet(QString::fromUtf8("font: 75 20pt \"DejaVu Sans\";"));
        label_24->setAlignment(Qt::AlignCenter);
        default_radio_button = new QRadioButton(bolus_screen);
        default_radio_button->setObjectName(QString::fromUtf8("default_radio_button"));
        default_radio_button->setGeometry(QRect(60, 200, 106, 23));
        default_radio_button->setChecked(true);
        extended_radio_button = new QRadioButton(bolus_screen);
        extended_radio_button->setObjectName(QString::fromUtf8("extended_radio_button"));
        extended_radio_button->setGeometry(QRect(60, 230, 106, 23));
        bolus_ok_button = new QPushButton(bolus_screen);
        bolus_ok_button->setObjectName(QString::fromUtf8("bolus_ok_button"));
        bolus_ok_button->setGeometry(QRect(540, 370, 83, 25));
        bolus_ok_button->setStyleSheet(QString::fromUtf8("background-color: rgb(38, 162, 105);"));
        home_screen = new QWidget(Device);
        home_screen->setObjectName(QString::fromUtf8("home_screen"));
        home_screen->setGeometry(QRect(10, 40, 691, 411));
        home_screen->setAutoFillBackground(false);
        home_screen->setStyleSheet(QString::fromUtf8("background-color: rgb(119, 118, 123);"));
        label_47 = new QLabel(home_screen);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(10, 70, 431, 331));
        label_47->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        label_48 = new QLabel(home_screen);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(450, 120, 161, 31));
        label_48->setStyleSheet(QString::fromUtf8("font: 12pt \"DejaVu Sans\";"));
        label_48->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        home_iob_label = new QLabel(home_screen);
        home_iob_label->setObjectName(QString::fromUtf8("home_iob_label"));
        home_iob_label->setGeometry(QRect(620, 120, 61, 31));
        home_iob_label->setStyleSheet(QString::fromUtf8("font: 12pt \"DejaVu Sans\";"));
        home_iob_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_50 = new QLabel(home_screen);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(450, 70, 181, 31));
        label_50->setStyleSheet(QString::fromUtf8("font: 12pt \"DejaVu Sans\";"));
        label_50->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_51 = new QLabel(home_screen);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(250, 20, 101, 31));
        label_51->setStyleSheet(QString::fromUtf8("font: 12pt \"DejaVu Sans\";"));
        label_51->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        home_time_label = new QLabel(home_screen);
        home_time_label->setObjectName(QString::fromUtf8("home_time_label"));
        home_time_label->setGeometry(QRect(360, 20, 61, 31));
        home_time_label->setStyleSheet(QString::fromUtf8("font: 12pt \"DejaVu Sans\";"));
        home_time_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        home_options_button = new QPushButton(home_screen);
        home_options_button->setObjectName(QString::fromUtf8("home_options_button"));
        home_options_button->setGeometry(QRect(480, 200, 161, 61));
        home_options_button->setStyleSheet(QString::fromUtf8("color: rgb(229, 165, 10);\n"
"background-color: rgb(61, 56, 70);\n"
"font: 75 16pt \"System-ui\";"));
        home_bolus_button = new QPushButton(home_screen);
        home_bolus_button->setObjectName(QString::fromUtf8("home_bolus_button"));
        home_bolus_button->setGeometry(QRect(480, 300, 161, 61));
        home_bolus_button->setStyleSheet(QString::fromUtf8("background-color: rgb(61, 56, 70);\n"
"font: 75 16pt \"System-ui\";\n"
"color: rgb(153, 193, 241);"));
        home_current_BG_label = new QLabel(home_screen);
        home_current_BG_label->setObjectName(QString::fromUtf8("home_current_BG_label"));
        home_current_BG_label->setGeometry(QRect(630, 70, 51, 31));
        home_current_BG_label->setStyleSheet(QString::fromUtf8("font: 12pt \"DejaVu Sans\";"));
        home_current_BG_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        battery = new QLabel(Device);
        battery->setObjectName(QString::fromUtf8("battery"));
        battery->setGeometry(QRect(10, 10, 61, 21));
        battery->setAutoFillBackground(false);
        battery->setStyleSheet(QString::fromUtf8("background-color: rgb(46, 194, 126);"));
        insulin_cartidge = new QLabel(Device);
        insulin_cartidge->setObjectName(QString::fromUtf8("insulin_cartidge"));
        insulin_cartidge->setGeometry(QRect(640, 10, 61, 21));
        insulin_cartidge->setAutoFillBackground(false);
        insulin_cartidge->setStyleSheet(QString::fromUtf8("background-color: rgb(98, 160, 234);"));
        home_button = new QPushButton(Device);
        home_button->setObjectName(QString::fromUtf8("home_button"));
        home_button->setGeometry(QRect(710, 180, 111, 111));
        home_button->setStyleSheet(QString::fromUtf8("font: 75 72pt \"DejaVu Sans\";\n"
"background-color: rgb(119, 118, 123);"));
        current_status_button = new QPushButton(Device);
        current_status_button->setObjectName(QString::fromUtf8("current_status_button"));
        current_status_button->setGeometry(QRect(590, 10, 31, 21));
        current_status_button->setStyleSheet(QString::fromUtf8("background-color: rgb(28, 113, 216);"));
        recharge_button = new QPushButton(centralwidget);
        recharge_button->setObjectName(QString::fromUtf8("recharge_button"));
        recharge_button->setGeometry(QRect(840, 10, 101, 51));
        insulin_refill_button = new QPushButton(centralwidget);
        insulin_refill_button->setObjectName(QString::fromUtf8("insulin_refill_button"));
        insulin_refill_button->setGeometry(QRect(840, 70, 101, 51));
        test_lock_button = new QPushButton(centralwidget);
        test_lock_button->setObjectName(QString::fromUtf8("test_lock_button"));
        test_lock_button->setGeometry(QRect(840, 210, 101, 31));
        test_log_button = new QPushButton(centralwidget);
        test_log_button->setObjectName(QString::fromUtf8("test_log_button"));
        test_log_button->setGeometry(QRect(840, 240, 101, 31));
        test_profile_list_button = new QPushButton(centralwidget);
        test_profile_list_button->setObjectName(QString::fromUtf8("test_profile_list_button"));
        test_profile_list_button->setGeometry(QRect(840, 270, 101, 31));
        test_current_status_button = new QPushButton(centralwidget);
        test_current_status_button->setObjectName(QString::fromUtf8("test_current_status_button"));
        test_current_status_button->setGeometry(QRect(840, 390, 101, 31));
        test_options_button = new QPushButton(centralwidget);
        test_options_button->setObjectName(QString::fromUtf8("test_options_button"));
        test_options_button->setGeometry(QRect(840, 330, 101, 31));
        test_setup_pin_button = new QPushButton(centralwidget);
        test_setup_pin_button->setObjectName(QString::fromUtf8("test_setup_pin_button"));
        test_setup_pin_button->setGeometry(QRect(840, 360, 101, 31));
        test_profile_button = new QPushButton(centralwidget);
        test_profile_button->setObjectName(QString::fromUtf8("test_profile_button"));
        test_profile_button->setGeometry(QRect(840, 300, 101, 31));
        test_bolus_button = new QPushButton(centralwidget);
        test_bolus_button->setObjectName(QString::fromUtf8("test_bolus_button"));
        test_bolus_button->setGeometry(QRect(840, 420, 101, 31));
        power_button = new QPushButton(centralwidget);
        power_button->setObjectName(QString::fromUtf8("power_button"));
        power_button->setGeometry(QRect(840, 130, 101, 51));
        MainWindow->setCentralWidget(centralwidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        pin1_button->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        pin2_button->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        pin3_button->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        submit_pin_button->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Logs", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Personal Profiles", nullptr));
        personal_profiles_list_add_button->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Current Status", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Profile Name", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Basal Rate", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Last Bolus Amount", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Last Bolus Time", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "Correction Factor", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Carb Ratio", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Target BG", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "Insulin Duration", nullptr));
        target_BG_label->setText(QString());
        profile_name_label->setText(QString());
        insulin_duration_label->setText(QString());
        carb_ratio_label->setText(QString());
        last_bolus_amount_label->setText(QString());
        last_bolus_time_label->setText(QString());
        basal_rate_label->setText(QString());
        correction_factor_label->setText(QString());
        label_7->setText(QCoreApplication::translate("MainWindow", "Options", nullptr));
        stop_resume_button->setText(QCoreApplication::translate("MainWindow", "Stop", nullptr));
        logs_screen_button->setText(QCoreApplication::translate("MainWindow", "Logs", nullptr));
        personal_profiles_screen_button->setText(QCoreApplication::translate("MainWindow", "Personal Profiles", nullptr));
        setup_pin_screen_button->setText(QCoreApplication::translate("MainWindow", "Setup Pin", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Setup PIN", nullptr));
        setup_pin1_button->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        setup_pin2_button->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        setup_pin3_button->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        current_pin_label->setText(QString());
        submit_setup_pin_button->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "Basal Rate", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "Carbohydrate Ratio", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "Correction Factor", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Target Glucose Level", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "Insulin Units for Quick Bolus", nullptr));
        delete_profile_button->setText(QCoreApplication::translate("MainWindow", "Delete", nullptr));
        activate_profile_button->setText(QCoreApplication::translate("MainWindow", "Activate", nullptr));
        edit_profile_button->setText(QCoreApplication::translate("MainWindow", "Edit", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "Current blood glucose level (mmol/L)", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "Carbohydrate Intake (grams)", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "Insulin dose (u)", nullptr));
        bolus_target_BG_label->setText(QCoreApplication::translate("MainWindow", "Target Blood Glucose Level", nullptr));
        bolus_insulin_duration_label->setText(QCoreApplication::translate("MainWindow", "Insulin Duration (hours)", nullptr));
        bolus_insulin_duration_textbox->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Manual Bolus Configuration", nullptr));
        default_radio_button->setText(QCoreApplication::translate("MainWindow", "Default", nullptr));
        extended_radio_button->setText(QCoreApplication::translate("MainWindow", "Extended", nullptr));
        bolus_ok_button->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_47->setText(QString());
        label_48->setText(QCoreApplication::translate("MainWindow", "Insulin on Board (u):", nullptr));
        home_iob_label->setText(QCoreApplication::translate("MainWindow", "< >", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindow", "Current BG (mmol/L):", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "Time Step:", nullptr));
        home_time_label->setText(QCoreApplication::translate("MainWindow", "< >", nullptr));
        home_options_button->setText(QCoreApplication::translate("MainWindow", "OPTIONS", nullptr));
        home_bolus_button->setText(QCoreApplication::translate("MainWindow", "BOLUS", nullptr));
        home_current_BG_label->setText(QCoreApplication::translate("MainWindow", "< >", nullptr));
        battery->setText(QCoreApplication::translate("MainWindow", "100%", nullptr));
        insulin_cartidge->setText(QCoreApplication::translate("MainWindow", "300 u", nullptr));
        home_button->setText(QCoreApplication::translate("MainWindow", "T", nullptr));
        current_status_button->setText(QCoreApplication::translate("MainWindow", "B", nullptr));
        recharge_button->setText(QCoreApplication::translate("MainWindow", "Recharge", nullptr));
        insulin_refill_button->setText(QCoreApplication::translate("MainWindow", "Insulin Refill", nullptr));
        test_lock_button->setText(QCoreApplication::translate("MainWindow", "Lock", nullptr));
        test_log_button->setText(QCoreApplication::translate("MainWindow", "Log", nullptr));
        test_profile_list_button->setText(QCoreApplication::translate("MainWindow", "Profiles List", nullptr));
        test_current_status_button->setText(QCoreApplication::translate("MainWindow", "Current Status", nullptr));
        test_options_button->setText(QCoreApplication::translate("MainWindow", "Options", nullptr));
        test_setup_pin_button->setText(QCoreApplication::translate("MainWindow", "Setup PIN", nullptr));
        test_profile_button->setText(QCoreApplication::translate("MainWindow", "Profile", nullptr));
        test_bolus_button->setText(QCoreApplication::translate("MainWindow", "Bolus", nullptr));
        power_button->setText(QCoreApplication::translate("MainWindow", "Power Off", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
